/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        surface: '#051424',
        'surface-dim': '#051424',
        'surface-bright': '#2c3a4c',
        'surface-container-lowest': '#010f1f',
        'surface-container-low': '#0d1c2d',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest': '#273647',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        outline: '#958ea0',
        'outline-variant': '#494454',
        'surface-tint': '#d0bcff',
        primary: '#d0bcff',
        'on-primary': '#3c0091',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'inverse-primary': '#6d3bd7',
        secondary: '#c3c6d6',
        'on-secondary': '#2c303c',
        'secondary-container': '#454956',
        'on-secondary-container': '#b5b8c7',
        tertiary: '#bcc7de',
        'on-tertiary': '#263143',
        'tertiary-container': '#8691a7',
        'on-tertiary-container': '#1f2a3c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5516be',
        'secondary-fixed': '#dfe2f2',
        'secondary-fixed-dim': '#c3c6d6',
        'on-secondary-fixed': '#171b27',
        'on-secondary-fixed-variant': '#434653',
        'tertiary-fixed': '#d8e3fb',
        'tertiary-fixed-dim': '#bcc7de',
        'on-tertiary-fixed': '#111c2d',
        'on-tertiary-fixed-variant': '#3c475a',
        background: '#051424',
        'on-background': '#d4e4fa',
        'surface-variant': '#273647',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        space: ['Space Grotesk', 'sans-serif'],
      },
      spacing: {
        sidebar: '260px',
      }
    },
  },
  plugins: [],
};
